spring.application.name=DemandaTech

spring.data.mongodb.uri=mongodb://localhost:27017/demandatech

spring.jpa.properties.hibernate.default_schema=demanda_tech
spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true

logging.level.org.hibernate.orm.jdbc.error=OFF
